"""Alembic environment generated by scripts/migration.py."""

from __future__ import annotations

import importlib
import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool


config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

SERVICE_PATH = Path(__file__).resolve().parents[1]
ROOT = SERVICE_PATH.parents[1]
for path in (
    SERVICE_PATH,
    ROOT / "shared" / "types",
    ROOT / "shared" / "inference-sdk",
):
    value = str(path)
    if value not in sys.path:
        sys.path.insert(0, value)


def load_dotenv(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_dotenv(ROOT / ".env")
load_dotenv(SERVICE_PATH / ".env")

config_module = config.get_main_option("app_config_module")
database_module = config.get_main_option("app_database_module")
metadata_expr = config.get_main_option("app_metadata")
model_imports = [
    name.strip()
    for name in config.get_main_option("app_model_imports", "").split(",")
    if name.strip()
]

for module_name in model_imports:
    importlib.import_module(module_name)

settings = importlib.import_module(config_module).settings
database = importlib.import_module(database_module)
target_metadata = database
for part in metadata_expr.split("."):
    target_metadata = getattr(target_metadata, part)

target_table_names = {table.name for table in target_metadata.tables.values()}


def include_name(name, type_, parent_names):
    if type_ == "table":
        return name in target_table_names
    return True


def include_object(object_, name, type_, reflected, compare_to):
    if type_ == "table":
        return name in target_table_names
    return True


config.set_main_option("sqlalchemy.url", settings.DATABASE_URL.replace("+asyncpg", ""))


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        include_name=include_name,
        include_object=include_object,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_name=include_name,
            include_object=include_object,
            compare_type=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
